apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    node.type: es-node-master
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      node.type: es-node-master
  template:
    metadata:
      labels:
        node.type: es-node-master
    spec:
      containers:
        - name: es-node-master-container
          env:
            - name: discovery.type
              value: single-node
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
